name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - feature/enabled-codeql

jobs:
  build-zephyr:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.28-branch
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: application
          submodules: recursive
          fetch-depth: 0
      
      - name: West and Zephyr setup
        run: |
          west init -l ./application
          west config --global update.narrow true
          west update 
          echo "ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-$ZSDK_VERSION" >> $GITHUB_ENV
      - name: Build b_u585i_iot02a
        run: |
          west build --pristine -b b_u585i_iot02a ./application -d build -- -DMODULE_EXT_ROOT=$(pwd)/application
