name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - feature/enabled-codeql

jobs:
  build-zephyr:
    runs-on: ubuntu-latest
    # container:
    #   image: ghcr.io/zephyrproject-rtos/ci:v0.28-branch
    #   options: --user root

    steps:
      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt install -y --no-install-recommends git curl cmake ninja-build gperf \
            ccache dfu-util device-tree-compiler wget python3-dev python3-venv python3-tk \
            xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1 unzip

      - name: Setup Python environment
        run: |
          python3 -m venv ~/zephyr-venv
          source ~/zephyr-venv/bin/activate
          pip install west

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: application
          submodules: recursive
          fetch-depth: 1
      
      - name: West and Zephyr setup
        run: |
          west init -l ./application
          west config --global update.narrow true
          west update -o=--depth=1 --group-filter=-tests,-samples,-bablesim,-docs
          echo "ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-$ZSDK_VERSION" >> $GITHUB_ENV
          west zephyr-export
          west packages pip --install
          west sdk install

      # Download CodeQL Coding Standards
      - name: Download CodeQL Coding Standards
        run: |
          # Download the latest coding standards packs
          curl -L -o coding-standards-codeql-packs.zip \
            "https://github.com/github/codeql-coding-standards/releases/download/v2.50.0/coding-standards-codeql-packs.zip"
          
          # Extract the packs
          unzip coding-standards-codeql-packs.zip
          ls -la

      # Initialize CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: c
          config-file: ./application/.github/codeql/codeql-config.yml

      - name: Build b_u585i_iot02a
        run: |
          west build --pristine -b b_u585i_iot02a ./application -d build -- -DMODULE_EXT_ROOT=$(pwd)/application

      # Perform CodeQL Analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
          upload: true          